# processing/actor_data.py
"""Mappings and blocklists for actors, malware, organizations, and locations."""

# Generic malware terms to ignore in detection
MALWARE_GENERIC = {
    "malware",
    "backdoor",
    "trojan",
    "worm",
    "virus",
    "exploit",
    "spyware",
    "ransomware",
    "rootkit",
    "botnet",
    "keylogger",
    "dropper",
    "loader",
    "payload",
    "implant",
    "adware",
    "infostealer",
    "stealer",
    "rat",
    "google play store",
    "google play",
    "play store",
    "play",
    "play ransomware",
    "app store",
    "github",
    "npm",
    "pypi",
}

# Additional terms to block from malware detection
MALWARE_BLOCKLIST = MALWARE_GENERIC | {
    "apt",
    "threat",
    "attack",
    "tool",
    "toolkit",
    "framework",
    "software",
    "code",
    "script",
    "binary",
    "executable",
    "file",
    "document",
    "email",
    "lockbit ransomware",
}

# Organizations or platforms to ignore as entities
ORG_BLOCKLIST = {
    "google",
    "google play",
    "google play store",
    "play store",
    "apple",
    "app store",
    "apple app store",
    "microsoft",
    "amazon",
    "meta",
    "facebook",
    "twitter",
    "x",
    "telegram",
    "whatsapp",
    "github",
    "npm",
    "pypi",
    "docker",
    "android",
    "ios",
    "windows",
    "linux",
    "the verge",
    "reuters",
    "bbc",
    "cnn",
    "techcrunch",
    "wired",
    "bloomberg",
    "play",
}

# Actor names to ignore (false positives)
ACTOR_BLOCKLIST = {
    "play",
    "play ransomware",
    "google",
    "apple",
    "microsoft",
    "amazon",
    "meta",
    "facebook",
    "twitter",
    "signal",
    "telegram",
    "github",
    "playcrypt",
    "hive",
    "grief",
    "cloak",
    # MITRE ATT&CK tactic IDs — not actors
    "ta0001",
    "ta0002",
    "ta0003",
    "ta0004",
    "ta0005",
    "ta0006",
    "ta0007",
    "ta0008",
    "ta0009",
    "ta0010",
    "ta0011",
    "ta0040",
    "ta0042",
    "ta0043",
    # parsing artifacts
    "ung0002 seqrite apt-team",
}

# Normalize location variations to canonical names
LOCATION_NORMALIZE = {
    # United States
    "us": "United States",
    "usa": "United States",
    "u.s.": "United States",
    "u.s": "United States",
    "the united states": "United States",
    "the u.s.": "United States",
    "the united states'": "United States",
    "the united states\u2019": "United States",
    "the united states\u2018": "United States",
    "the united states\u2019s": "United States",
    "america": "United States",
    "u.s.-based": "United States",
    "michigan": "United States",
    "los angeles": "United States",
    "city of los angels": "United States",
    "city of los angeles": "United States",
    "scottsdale": "United States",
    "bay area": "United States",
    "arizona": "United States",
    "california": "United States",
    "north carolina": "United States",
    "la": "United States",
    "foster city": "United States",
    "cornelius": "United States",
    # United Kingdom
    "uk": "United Kingdom",
    "u.k.": "United Kingdom",
    "u.k": "United Kingdom",
    "the united kingdom": "United Kingdom",
    "britain": "United Kingdom",
    "great britain": "United Kingdom",
    # North Korea
    "north korea's": "North Korea",
    "north koreas": "North Korea",
    "north korea\u2019s": "North Korea",
    "dprk": "North Korea",
    "democratic people's republic of korea": "North Korea",
    # South Korea
    "republic of korea": "South Korea",
    "rok": "South Korea",
    "south korea's": "South Korea",
    "south korea s": "South Korea",
    "south korea\u2019s": "South Korea",
    # Russia
    "russian federation": "Russia",
    "the russian federation": "Russia",
    "perm": "Russia",
    # China
    "prc": "China",
    "people's republic of china": "China",
    "wuhan": "China",
    "beijing": "China",
    # Iran
    "islamic republic of iran": "Iran",
    "the iran": "Iran",
    # Middle East
    "the middle east": "Middle East",
    "middle eastern": "Middle East",
    "the gulf": "Middle East",
    "gulf states": "Middle East",
    "the gulf states": "Middle East",
    "gulf": "Middle East",
    "the persian gulf": "Middle East",
    "persian gulf": "Middle East",
    "mena": "Middle East",
    # UAE
    "dubai": "United Arab Emirates",
    "uae": "United Arab Emirates",
    "emirates": "United Arab Emirates",
    # Europe
    "eu": "Europe",
    "european union": "Europe",
    "european": "Europe",
    "western europe": "Europe",
    # Southeast Asia
    "southeast asi": "Southeast Asia",
    "south east asia": "Southeast Asia",
    "se asia": "Southeast Asia",
    "the southeast asia": "Southeast Asia",
    # Latin America
    "latam": "Latin America",
    "latin america": "Latin America",
    # Asia-Pacific
    "apac": "Asia-Pacific",
    # Germany (foreign language variants)
    "deutschland": "Germany",
    # Netherlands
    "the netherlands": "Netherlands",
    # Canada
    "kanada": "Canada",
    # North America
    "nordamerika": "North America",
    # Kazakhstan
    "karaganda": "Kazakhstan",
    # Spain
    "madrid": "Spain",
    # Asia
    "south asia": "South Asia",
    "central asia": "Central Asia",
}

# Locations that are too generic or non-geographic
LOCATION_BLOCKLIST = {
    "internet",
    "web",
    "online",
    "cyber",
    "network",
    "cloud",
    "dark web",
    "darkweb",
    "the internet",
    "github",
    "windows",
    "android",
    "ios",
    "linux",
    "macos",
    # too vague / partial
    "south",
    "central",
    "southeast",
    "americas",
    "global",
    "worldwide",
    "international",
    "region",
    "domestic",
    "foreign",
    "local",
    "atlantic",
    # not locations
    "suojelupoliisi",
    "vojensk\u00e9",
    "go",
    "the southern district of new york",
    "southern district of new york",
}

# Map aliases/nicknames to canonical MITRE threat actor names
ACTOR_NORMALIZE = {
    # APT28
    "fancy bear": "APT28",
    "strontium": "APT28",
    "sofacy": "APT28",
    "pawn storm": "APT28",
    "sednit": "APT28",
    "forest blizzard": "APT28",
    "iron twilight": "APT28",
    "uac-0001": "APT28",
    # APT29
    "cozy bear": "APT29",
    "midnight blizzard": "APT29",
    "nobelium": "APT29",
    "the dukes": "APT29",
    # APT41
    "silver dragon": "APT41",
    "wicked panda": "APT41",
    "brass typhoon": "APT41",
    "barium": "APT41",
    "double dragon": "APT41",
    # APT37 / ScarCruft
    "scarcruft": "APT37",
    "inky squid": "APT37",
    "inkysquid": "APT37",
    "reaper": "APT37",
    "group123": "APT37",
    "apt-c-28": "APT37",
    # Lazarus Group
    "lazarus": "Lazarus Group",
    "lazarus group": "Lazarus Group",
    "lazarus it workers": "Lazarus Group",
    "hidden cobra": "Lazarus Group",
    "guardians of peace": "Lazarus Group",
    "zinc": "Lazarus Group",
    "the Lazarus Group": "Lazarus Group",
    "the lazarus group": "Lazarus Group",
    # Sandworm Team
    "sandworm": "Sandworm Team",
    "sandworm team": "Sandworm Team",
    "voodoo bear": "Sandworm Team",
    "telebots": "Sandworm Team",
    "electrum": "Sandworm Team",
    "iron viking": "Sandworm Team",
    "seashell blizzard": "Sandworm Team",
    # Magic Hound
    "charming kitten": "Magic Hound",
    "phosphorus": "Magic Hound",
    "ta453": "Magic Hound",
    "cobalt illusion": "Magic Hound",
    "apt35": "Magic Hound",
    # MuddyWater
    "static kitten": "MuddyWater",
    "mercury": "MuddyWater",
    "earth vetala": "MuddyWater",
    "seedworm": "MuddyWater",
    "muddywater": "MuddyWater",
    "muddywater apt": "MuddyWater",
    # OilRig
    "apt34": "OilRig",
    "helix kitten": "OilRig",
    "cobalt gypsy": "OilRig",
    "crambus": "OilRig",
    "oilrig": "OilRig",
    # Kimsuky
    "velvet chollima": "Kimsuky",
    "emerald sleet": "Kimsuky",
    "black banshee": "Kimsuky",
    "thallium": "Kimsuky",
    "kimsuky": "Kimsuky",
    # Volt Typhoon
    "bronze silhouette": "Volt Typhoon",
    "vanguard panda": "Volt Typhoon",
    "insidious taurus": "Volt Typhoon",
    # Salt Typhoon
    "salt typhoon": "Salt Typhoon",
    "ghost emperor": "Salt Typhoon",
    "famousparrow": "Salt Typhoon",
    # Turla
    "snake": "Turla",
    "uroburos": "Turla",
    "waterbug": "Turla",
    "iron hunter": "Turla",
    "turla": "Turla",
    "secret blizzard": "Turla",
    # Transparent Tribe
    "apt36": "Transparent Tribe",
    "transparent tribe": "Transparent Tribe",
    "mythic leopard": "Transparent Tribe",
    "copper fieldstone": "Transparent Tribe",
    # Scattered Spider
    "octo tempest": "Scattered Spider",
    "roasted 0ktapus": "Scattered Spider",
    "unc3944": "Scattered Spider",
    "scattered spider": "Scattered Spider",
    # ShinyHunters
    "shinyhunters": "ShinyHunters",
    "unc6240": "ShinyHunters",
    "unc6661": "ShinyHunters",
    "unc6671": "ShinyHunters",
    # Gamaredon Group
    "gamaredon": "Gamaredon Group",
    "primitive bear": "Gamaredon Group",
    "actinium": "Gamaredon Group",
    "iron tilden": "Gamaredon Group",
    # Mustang Panda
    "bronze president": "Mustang Panda",
    "earth preta": "Mustang Panda",
    "mustang panda": "Mustang Panda",
    "stately taurus": "Mustang Panda",
    "unc6384": "Mustang Panda",
    # Leviathan / APT40
    "ta423": "Leviathan",
    "leviathan": "Leviathan",
    "apt40": "Leviathan",
    # HAFNIUM
    "hafnium": "HAFNIUM",
    "silk typhoon": "HAFNIUM",
    # Sidewinder
    "sidewinder": "Sidewinder",
    "rattlesnake": "Sidewinder",
    "razor tiger": "Sidewinder",
    # APT42
    "apt42": "APT42",
    "calanque": "APT42",
    # APT33
    "apt33": "APT33",
    "elfin": "APT33",
    "refined kitten": "APT33",
    "magnallium": "APT33",
    # COLDRIVER / Star Blizzard
    "coldriver": "Star Blizzard",
    "star blizzard": "Star Blizzard",
    "callisto": "Star Blizzard",
    # DarkSide
    "darkside": "DarkSide",
    # Fox Kitten
    "fox kitten": "Fox Kitten",
    "pioneer kitten": "Fox Kitten",
    # Handala Hack
    "handala hack": "Handala Hack",
    "handala": "Handala Hack",
    "contagious interview": "Contagious Interview",
    "lapsus$": "LAPSUS$",
    "tropic trooper": "Tropic Trooper",
    "lotus blossom": "Lotus Blossom",
    "warlock ransomware group": "Warlock",
    "warlock": "Warlock",
    "dragonforce malaysia": "DragonForce",
    "dragonforce": "DragonForce",
    "silent lynx": "Silent Lynx",
    "dragonclone": "DragonClone",
    "ung0002": "UNG0002",
    "bqtlock": "BQTLock",
    # vendor/CERT named groups
    "boggy serpens": "Boggy Serpens",
    "dust specter": "Dust Specter",
    "graycharlie": "GrayCharlie",
    "purplebravo": "PurpleBravo",
    "rublevka team": "Rublevka Team",
    "stan ghouls": "Stan Ghouls",
    "kongtuke": "KongTuke",
    "udpgangster": "UDPGangster",
    "amaranth-dragon": "Amaranth-Dragon",
    "camelclone": "CamelClone",
    "imperial kitten": "Imperial Kitten",
    "tortoiseshell": "Tortoiseshell",
    "agonizing serpens": "Agonizing Serpens",
    "predatory sparrow": "Predatory Sparrow",
    "hydra saiga": "Hydra Saiga",
    "laundry bear": "Laundry Bear",
    "cadet blizzard": "Cadet Blizzard",
    "blind eagle": "Blind Eagle",
    "el machete": "El Machete",
    "bahamut": "Bahamut",
    "worldleaks": "WorldLeaks",
    "the gentlemen": "The Gentlemen",
    # ransomware groups
    "lockbit": "LockBit",
    "alphv": "ALPHV",
    "blackcat": "ALPHV",
    "cl0p": "Cl0p",
    "clop": "Cl0p",
    "akira": "Akira",
    "rhysida": "Rhysida",
    "blackbyte": "BlackByte",
    "blacksuit": "BlackSuit",
    "royal ransomware": "Royal",
    "hunters international": "Hunters International",
    "medusa ransomware": "Medusa",
    "medusa": "Medusa",
    "interlock": "Interlock",
    "beast ransomware": "Beast",
    "beast": "Beast",
    # Storm clusters
    "storm-0501": "Storm-0501",
    "storm-1811": "Storm-1811",
    "storm-2561": "Storm-2561",
    "storm-2603": "Storm-2603",
    # UAT / UNC IDs
    "uat-9244": "UAT-9244",
    "uat-8616": "UAT-8616",
}

# Known country of origin for MITRE threat actor groups
MITRE_ORIGINS = {
    # Russia
    "APT28": "Russia",
    "APT29": "Russia",
    "Sandworm Team": "Russia",
    "Turla": "Russia",
    "Gamaredon Group": "Russia",
    "Ember Bear": "Russia",
    "Saint Bear": "Russia",
    "Star Blizzard": "Russia",
    "TEMP.Veles": "Russia",
    "Dragonfly": "Russia",
    "Indrik Spider": "Russia",
    "GCMAN": "Russia",
    "Carbanak": "Russia",
    "Silence": "Russia",
    "RTM": "Russia",
    "DarkVishnya": "Russia",
    "GOLD SOUTHFIELD": "Russia",
    "Wizard Spider": "Russia",
    "PROMETHIUM": "Russia",
    "Storm-0501": "Russia",
    "Storm-1811": "Russia",
    "NEODYMIUM": "Russia",
    "Strider": "Russia",
    "Cobalt Group": "Russia",
    "TA505": "Russia",
    "FIN7": "Russia",
    "Laundry Bear": "Russia",
    "Cadet Blizzard": "Russia",
    "Stan Ghouls": "Russia",
    "Hydra Saiga": "Russia",
    # China
    "APT1": "China",
    "APT3": "China",
    "APT5": "China",
    "APT12": "China",
    "APT16": "China",
    "APT17": "China",
    "APT18": "China",
    "APT19": "China",
    "APT30": "China",
    "APT41": "China",
    "Volt Typhoon": "China",
    "Salt Typhoon": "China",
    "RedEcho": "China",
    "Velvet Ant": "China",
    "Mustang Panda": "China",
    "Leviathan": "China",
    "HAFNIUM": "China",
    "GALLIUM": "China",
    "Winnti Group": "China",
    "BRONZE BUTLER": "China",
    "Daggerfly": "China",
    "Aquatic Panda": "China",
    "Naikon": "China",
    "Elderwood": "China",
    "admin@338": "China",
    "BackdoorDiplomacy": "China",
    "BlackTech": "China",
    "Chimera": "China",
    "Deep Panda": "China",
    "DragonOK": "China",
    "Earth Lusca": "China",
    "Ke3chang": "China",
    "Lotus Blossom": "China",
    "LuminousMoth": "China",
    "menuPass": "China",
    "Moafee": "China",
    "Mofang": "China",
    "Putter Panda": "China",
    "Rancor": "China",
    "Rocke": "China",
    "Scarlet Mimic": "China",
    "Suckfly": "China",
    "Threat Group-3390": "China",
    "Tonto Team": "China",
    "ToddyCat": "China",
    "Tropic Trooper": "China",
    "UNC3886": "China",
    "Water Galura": "China",
    "Whitefly": "China",
    "Bouncing Golf": "China",
    "IndigoZebra": "China",
    "Thrip": "China",
    "Axiom": "China",
    "Sowbug": "China",
    "ZIRCONIUM": "China",
    "Cinnamon Tempest": "China",
    "Threat Group-1314": "China",
    "TA459": "China",
    "Aoqin Dragon": "China",
    "UAT-9244": "China",
    "Amaranth-Dragon": "China",
    "CamelClone": "China",
    "Dust Specter": "China",
    "DragonClone": "China",
    # North Korea
    "APT37": "North Korea",
    "APT38": "North Korea",
    "Lazarus Group": "North Korea",
    "Kimsuky": "North Korea",
    "Andariel": "North Korea",
    "Moonstone Sleet": "North Korea",
    "Contagious Interview": "North Korea",
    "AppleJeus": "North Korea",
    "Higaisa": "North Korea",
    "PLATINUM": "North Korea",
    # Iran
    "APT33": "Iran",
    "APT39": "Iran",
    "APT42": "Iran",
    "OilRig": "Iran",
    "MuddyWater": "Iran",
    "Magic Hound": "Iran",
    "Fox Kitten": "Iran",
    "CURIUM": "Iran",
    "HEXANE": "Iran",
    "Cleaver": "Iran",
    "Ajax Security Team": "Iran",
    "CopyKittens": "Iran",
    "Ferocious Kitten": "Iran",
    "Leafminer": "Iran",
    "Moses Staff": "Iran",
    "CyberAv3ngers": "Iran",
    "Agrius": "Iran",
    "Silent Librarian": "Iran",
    "DarkHydrus": "Iran",
    "WIRTE": "Iran",
    "Handala Hack": "Iran",
    "Imperial Kitten": "Iran",
    "Tortoiseshell": "Iran",
    "Agonizing Serpens": "Iran",
    "Boggy Serpens": "Iran",
    # Pakistan
    "Transparent Tribe": "Pakistan",
    "Sidewinder": "Pakistan",
    "Gorgon Group": "Pakistan",
    "SideCopy": "Pakistan",
    "APT-C-23": "Pakistan",
    "The White Company": "Pakistan",
    # India
    "Patchwork": "India",
    "Confucius": "India",
    "BITTER": "India",
    "Bahamut": "India",
    # Vietnam
    "APT32": "Vietnam",
    # Lebanon
    "POLONIUM": "Lebanon",
    "Volatile Cedar": "Lebanon",
    "Dark Caracal": "Lebanon",
    # Palestine
    "Molerats": "Palestine",
    "APT-C-36": "Palestine",
    # Belarus
    "MoustachedBouncer": "Belarus",
    "UNC788": "Belarus",
    # Turkey
    "Sea Turtle": "Turkey",
    # UAE
    "Stealth Falcon": "United Arab Emirates",
    # South America
    "Machete": "Colombia",
    "Malteiro": "Brazil",
    "Blind Eagle": "Colombia",
    "El Machete": "Colombia",
    # United States
    "Equation": "United States",
    "Scattered Spider": "United States",
    "ALLANITE": "United States",
    # United Kingdom
    "LAPSUS$": "United Kingdom",
    # Germany
    "TeamTNT": "Germany",
    # South Korea
    "Darkhotel": "South Korea",
    # Israel
    "Predatory Sparrow": "Israel",
    # Central Asia
    "Silent Lynx": "Central Asia",
    # Unknown / criminal / unattributed
    "Play": "Unknown",
    "Akira": "Unknown",
    "BlackByte": "Unknown",
    "INC Ransom": "Unknown",
    "FIN4": "Unknown",
    "FIN5": "Unknown",
    "FIN6": "Unknown",
    "FIN8": "Unknown",
    "FIN10": "Unknown",
    "FIN13": "Unknown",
    "Blue Mockingbird": "Unknown",
    "Orangeworm": "Unknown",
    "TA2541": "Unknown",
    "TA551": "Unknown",
    "TA577": "Unknown",
    "TA578": "Unknown",
    "Evilnum": "Unknown",
    "Medusa Group": "Unknown",
    "Metador": "Unknown",
    "Mustard Tempest": "Unknown",
    "Nomadic Octopus": "Unknown",
    "PittyTiger": "Unknown",
    "Poseidon Group": "Unknown",
    "EXOTIC LILY": "Unknown",
    "Group5": "Unknown",
    "Windigo": "Unknown",
    "Winter Vivern": "Unknown",
    "BlackOasis": "Unknown",
    "RedCurl": "Unknown",
    "SilverTerrier": "Unknown",
    "LazyScripter": "Unknown",
    "Windshift": "Unknown",
    "Inception": "Unknown",
    "UNC6353": "Unknown",
    "UNG0002": "Unknown",
    "DarkSide": "Unknown",
    "LockBit": "Unknown",
    "ALPHV": "Unknown",
    "Cl0p": "Unknown",
    "Rhysida": "Unknown",
    "Medusa": "Unknown",
    "BlackSuit": "Unknown",
    "Royal": "Unknown",
    "Hunters International": "Unknown",
    "Interlock": "Unknown",
    "Warlock": "Unknown",
    "Beast": "Unknown",
    "BQTLock": "Unknown",
    "DragonForce": "Unknown",
    "GrayCharlie": "Unknown",
    "PurpleBravo": "Unknown",
    "Rublevka Team": "Unknown",
    "KongTuke": "Unknown",
    "UDPGangster": "Unknown",
    "WorldLeaks": "Unknown",
    "The Gentlemen": "Unknown",
    "ShinyHunters": "Unknown",
    "UAT-8616": "Unknown",
    "Storm-2561": "Unknown",
    "Storm-2603": "Unknown",
}

# Lowercase version of MITRE_ORIGINS for NLP matching at extraction time
ACTOR_ORIGINS = {k.lower(): v for k, v in MITRE_ORIGINS.items()}
