# processing/actor_data.py
"""Mappings and blocklists for actors, malware, organizations, and locations."""

# Generic malware terms to ignore in detection
MALWARE_GENERIC = {
    "malware",
    "backdoor",
    "trojan",
    "worm",
    "virus",
    "exploit",
    "spyware",
    "ransomware",
    "rootkit",
    "botnet",
    "keylogger",
    "dropper",
    "loader",
    "payload",
    "implant",
    "adware",
    "infostealer",
    "stealer",
    "rat",
    "google play store",
    "google play",
    "play store",
    "play",
    "play ransomware",
    "app store",
    "github",
    "npm",
    "pypi",
}

# Additional terms to block from malware detection
MALWARE_BLOCKLIST = MALWARE_GENERIC | {
    "apt",
    "threat",
    "attack",
    "tool",
    "toolkit",
    "framework",
    "software",
    "code",
    "script",
    "binary",
    "executable",
    "file",
    "document",
    "email",
}

# Organizations or platforms to ignore as entities
ORG_BLOCKLIST = {
    "google",
    "google play",
    "google play store",
    "play store",
    "apple",
    "app store",
    "apple app store",
    "microsoft",
    "amazon",
    "meta",
    "facebook",
    "twitter",
    "x",
    "telegram",
    "whatsapp",
    "github",
    "npm",
    "pypi",
    "docker",
    "android",
    "ios",
    "windows",
    "linux",
    "the verge",
    "reuters",
    "bbc",
    "cnn",
    "techcrunch",
    "wired",
    "bloomberg",
    "play",
}

# Actor names to ignore (false positives)
ACTOR_BLOCKLIST = {
    "play",
    "play ransomware",
    "google",
    "apple",
    "microsoft",
    "amazon",
    "meta",
    "facebook",
    "twitter",
    "signal",
    "telegram",
    "github",
    "playcrypt",
}

# Normalize location variations to canonical names
LOCATION_NORMALIZE = {
    "us": "United States",
    "u.s.": "United States",
    "u.s": "United States",
    "the united states": "United States",
    "the u.s.": "United States",
    "america": "United States",
    "uk": "United Kingdom",
    "u.k.": "United Kingdom",
    "u.k": "United Kingdom",
    "the united kingdom": "United Kingdom",
    "britain": "United Kingdom",
    "great britain": "United Kingdom",
    "north korea's": "North Korea",
    "north koreas": "North Korea",
    "dprk": "North Korea",
    "democratic people's republic of korea": "North Korea",
    "republic of korea": "South Korea",
    "rok": "South Korea",
    "russian federation": "Russia",
    "the russian federation": "Russia",
    "prc": "China",
    "people's republic of china": "China",
    "islamic republic of iran": "Iran",
    "the iran": "Iran",
    "the middle east": "Middle East",
    "middle eastern": "Middle East",
    "the gulf": "Middle East",
    "gulf states": "Middle East",
    "gulf": "Middle East",
    "dubai": "United Arab Emirates",
    "eu": "Europe",
    "european union": "Europe",
    "european": "Europe",
    "southeast asi": "Southeast Asia",
    "south east asia": "Southeast Asia",
    "se asia": "Southeast Asia",
    "uae": "United Arab Emirates",
    "emirates": "United Arab Emirates",
}

# Locations that are too generic or non-geographic
LOCATION_BLOCKLIST = {
    "internet",
    "web",
    "online",
    "cyber",
    "network",
    "cloud",
    "dark web",
    "darkweb",
    "the internet",
    "github",
    "windows",
    "android",
    "ios",
    "linux",
    "macos",
}

# Map aliases/nicknames to canonical MITRE threat actor names
ACTOR_NORMALIZE = {
    # APT28 aliases
    "fancy bear": "APT28",  # Fancy Bear
    "strontium": "APT28",  # Strontium
    "sofacy": "APT28",  # Sofacy
    "pawn storm": "APT28",  # Pawn Storm
    "sednit": "APT28",  # Sednit
    "forest blizzard": "APT28",  # Forest Blizzard
    "iron twilight": "APT28",  # Iron Twilight
    "uac-0001": "APT28",  # UAC-0001
    # APT29 aliases
    "cozy bear": "APT29",  # Cozy Bear
    "midnight blizzard": "APT29",  # Midnight Blizzard
    "nobelium": "APT29",  # Nobelium
    "the dukes": "APT29",  # The Dukes
    # APT41 aliases
    "silver dragon": "APT41",
    "wicked panda": "APT41",
    "brass typhoon": "APT41",
    "barium": "APT41",
    "double dragon": "APT41",
    # APT37 aliases
    "scarcruft": "APT37",
    "inky squid": "APT37",
    "inkysquid": "APT37",
    "reaper": "APT37",
    "group123": "APT37",
    # Lazarus Group aliases
    "lazarus": "Lazarus Group",
    "hidden cobra": "Lazarus Group",
    "guardians of peace": "Lazarus Group",
    "zinc": "Lazarus Group",
    # Sandworm Team aliases
    "sandworm": "Sandworm Team",
    "voodoo bear": "Sandworm Team",
    "telebots": "Sandworm Team",
    "electrum": "Sandworm Team",
    "iron viking": "Sandworm Team",
    # Magic Hound aliases
    "charming kitten": "Magic Hound",
    "phosphorus": "Magic Hound",
    "ta453": "Magic Hound",
    "cobalt illusion": "Magic Hound",
    "apt35": "Magic Hound",
    # MuddyWater aliases
    "static kitten": "MuddyWater",
    "mercury": "MuddyWater",
    "earth vetala": "MuddyWater",
    "seedworm": "MuddyWater",
    "muddywater": "MuddyWater",
    # OilRig aliases
    "apt34": "OilRig",
    "helix kitten": "OilRig",
    "cobalt gypsy": "OilRig",
    "crambus": "OilRig",
    "oilrig": "OilRig",
    # Kimsuky aliases
    "velvet chollima": "Kimsuky",
    "emerald sleet": "Kimsuky",
    "black banshee": "Kimsuky",
    "thallium": "Kimsuky",
    # Volt Typhoon aliases
    "bronze silhouette": "Volt Typhoon",
    "vanguard panda": "Volt Typhoon",
    "insidious taurus": "Volt Typhoon",
    # Turla aliases
    "snake": "Turla",
    "uroburos": "Turla",
    "waterbug": "Turla",
    "iron hunter": "Turla",
    # Transparent Tribe aliases
    "apt36": "Transparent Tribe",
    "transparent tribe": "Transparent Tribe",
    "mythic leopard": "Transparent Tribe",
    "copper fieldstone": "Transparent Tribe",
    # Scattered Spider aliases
    "octo tempest": "Scattered Spider",
    "roasted 0ktapus": "Scattered Spider",
    "unc3944": "Scattered Spider",
    # Gamaredon Group aliases
    "gamaredon": "Gamaredon Group",
    "primitive bear": "Gamaredon Group",
    "actinium": "Gamaredon Group",
    "iron tilden": "Gamaredon Group",
    # Play aliases
    "play ransomware": "Play",
    "playcrypt": "Play",
    # UAT-9244 aliases
    "uat-9244": "UAT-9244",
}

# Known country of origin for MITRE threat actor groups
MITRE_ORIGINS = {
    # Russia
    "APT28": "Russia",
    "APT29": "Russia",
    "Sandworm Team": "Russia",
    "Turla": "Russia",
    "Gamaredon Group": "Russia",
    "Ember Bear": "Russia",
    "Saint Bear": "Russia",
    "Star Blizzard": "Russia",
    "TEMP.Veles": "Russia",
    "Dragonfly": "Russia",
    "Indrik Spider": "Russia",
    "GCMAN": "Russia",
    "Carbanak": "Russia",
    "Silence": "Russia",
    "RTM": "Russia",
    "DarkVishnya": "Russia",
    "GOLD SOUTHFIELD": "Russia",
    "Wizard Spider": "Russia",
    "PROMETHIUM": "Russia",
    "Storm-0501": "Russia",
    "Storm-1811": "Russia",
    "NEODYMIUM": "Russia",
    "Strider": "Russia",
    "Cobalt Group": "Russia",
    "TA505": "Russia",
    "FIN7": "Russia",
    # China
    "APT1": "China",
    "APT3": "China",
    "APT5": "China",
    "APT12": "China",
    "APT16": "China",
    "APT17": "China",
    "APT18": "China",
    "APT19": "China",
    "APT30": "China",
    "APT41": "China",
    "Volt Typhoon": "China",
    "Salt Typhoon": "China",
    "RedEcho": "China",
    "Velvet Ant": "China",
    "Mustang Panda": "China",
    "Leviathan": "China",
    "HAFNIUM": "China",
    "GALLIUM": "China",
    "Winnti Group": "China",
    "BRONZE BUTLER": "China",
    "Daggerfly": "China",
    "Aquatic Panda": "China",
    "Naikon": "China",
    "Elderwood": "China",
    "admin@338": "China",
    "BackdoorDiplomacy": "China",
    "BlackTech": "China",
    "Chimera": "China",
    "Deep Panda": "China",
    "DragonOK": "China",
    "Earth Lusca": "China",
    "Ke3chang": "China",
    "Lotus Blossom": "China",
    "LuminousMoth": "China",
    "menuPass": "China",
    "Moafee": "China",
    "Mofang": "China",
    "Putter Panda": "China",
    "Rancor": "China",
    "Rocke": "China",
    "Scarlet Mimic": "China",
    "Suckfly": "China",
    "Threat Group-3390": "China",
    "Tonto Team": "China",
    "ToddyCat": "China",
    "Tropic Trooper": "China",
    "UNC3886": "China",
    "Water Galura": "China",
    "Whitefly": "China",
    "Bouncing Golf": "China",
    "IndigoZebra": "China",
    "Thrip": "China",
    "Axiom": "China",
    "Sowbug": "China",
    "ZIRCONIUM": "China",
    "Cinnamon Tempest": "China",
    "Threat Group-1314": "China",
    "TA459": "China",
    "Aoqin Dragon": "China",
    "UAT-9244": "China",
    # North Korea
    "APT37": "North Korea",
    "APT38": "North Korea",
    "Lazarus Group": "North Korea",
    "Kimsuky": "North Korea",
    "Andariel": "North Korea",
    "Moonstone Sleet": "North Korea",
    "Contagious Interview": "North Korea",
    "AppleJeus": "North Korea",
    "Higaisa": "North Korea",
    "PLATINUM": "North Korea",
    # Iran
    "APT33": "Iran",
    "APT39": "Iran",
    "APT42": "Iran",
    "OilRig": "Iran",
    "MuddyWater": "Iran",
    "Magic Hound": "Iran",
    "Fox Kitten": "Iran",
    "CURIUM": "Iran",
    "HEXANE": "Iran",
    "Cleaver": "Iran",
    "Ajax Security Team": "Iran",
    "CopyKittens": "Iran",
    "Ferocious Kitten": "Iran",
    "Leafminer": "Iran",
    "Moses Staff": "Iran",
    "CyberAv3ngers": "Iran",
    "Agrius": "Iran",
    "Silent Librarian": "Iran",
    "DarkHydrus": "Iran",
    "WIRTE": "Iran",
    # Pakistan
    "Transparent Tribe": "Pakistan",
    "Sidewinder": "Pakistan",
    "Gorgon Group": "Pakistan",
    "SideCopy": "Pakistan",
    "APT-C-23": "Pakistan",
    "The White Company": "Pakistan",
    # India
    "Patchwork": "India",
    "Confucius": "India",
    "BITTER": "India",
    # Vietnam
    "APT32": "Vietnam",
    # Lebanon
    "POLONIUM": "Lebanon",
    "Volatile Cedar": "Lebanon",
    "Dark Caracal": "Lebanon",
    # Palestine
    "Molerats": "Palestine",
    "APT-C-36": "Palestine",
    # Belarus
    "MoustachedBouncer": "Belarus",
    "UNC788": "Belarus",
    # Turkey
    "Sea Turtle": "Turkey",
    # UAE
    "Stealth Falcon": "United Arab Emirates",
    # South America
    "Machete": "Colombia",
    "Malteiro": "Brazil",
    # United States
    "Equation": "United States",
    "Scattered Spider": "United States",
    "ALLANITE": "United States",
    # United Kingdom
    "LAPSUS$": "United Kingdom",
    # Germany
    "TeamTNT": "Germany",
    # South Korea
    "Darkhotel": "South Korea",
    # Unknown — criminal or unattributed groups
    "Play": "Unknown",
    "Akira": "Unknown",
    "BlackByte": "Unknown",
    "INC Ransom": "Unknown",
    "FIN4": "Unknown",
    "FIN5": "Unknown",
    "FIN6": "Unknown",
    "FIN8": "Unknown",
    "FIN10": "Unknown",
    "FIN13": "Unknown",
    "Blue Mockingbird": "Unknown",
    "Orangeworm": "Unknown",
    "TA2541": "Unknown",
    "TA551": "Unknown",
    "TA577": "Unknown",
    "TA578": "Unknown",
    "Evilnum": "Unknown",
    "Medusa Group": "Unknown",
    "Metador": "Unknown",
    "Mustard Tempest": "Unknown",
    "Nomadic Octopus": "Unknown",
    "PittyTiger": "Unknown",
    "Poseidon Group": "Unknown",
    "EXOTIC LILY": "Unknown",
    "Group5": "Unknown",
    "Windigo": "Unknown",
    "Winter Vivern": "Unknown",
    "BlackOasis": "Unknown",
    "RedCurl": "Unknown",
    "SilverTerrier": "Unknown",
    "LazyScripter": "Unknown",
    "Windshift": "Unknown",
    "Inception": "Unknown",
    "UNC6353": "Unknown",
}

ACTOR_ORIGINS = {k.lower(): v for k, v in MITRE_ORIGINS.items()}
