name: Tests

on:
  push:
    branches: [ main, master]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        environment-file: environment.yaml
        activate-environment: osint
    
    - name: Setup config file
      shell: bash -l {0}
      run: |
        cp config/settings.example.yaml config/settings.yaml
    
    - name: Install SpaCy model
      shell: bash -l {0}
      run: |
        conda activate osint
        python -m spacy download en_core_web_trf
    
    - name: Run tests with coverage
      shell: bash -l {0}
      run: |
        conda activate osint
        pytest --cov --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        branch: main